### ISSUE TITLE
Webserver crashes on Requesting a page.

### ISSUE THREAD

**Issue by rainerzufalldererste** [rainerzufalldererste/LamestWebserver#63]
`Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at LamestWebserver.Core.ThreadedWorker..ctor(UInt32 workerCount)
   at LamestWebserver.WebServer.<>c.<.ctor>b__40_0() in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\WebServer.cs:line 31
   at LamestWebserver.Core.Singleton`1.get_Instance() in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\Core\Singleton.cs:line 33
   at LamestWebserver.WebServer.HandleTcpListener() in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\WebServer.cs:line 378
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by rainerzufalldererste** [comment]
This happened in an older version, but might still be helpful

**Comment by rainerzufalldererste** [comment]
Unhandled Exception: 24/04/2018 16:15:31 [Information] \\\\ A new FlushableMemoryPool has been initialized.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at LamestWebserver.UI.HHeadline..ctor(String text, Int32 level)
   at lukipedia.Lukipedia.GetElement(SessionData sessionData) in H:\git\private\lukipedia\lukipedia\lukipedia\Lukipedia.cs:line 91
   at LamestWebserver.ElementResponse.GetContents(SessionData sessionData) in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\PageResponse.cs:line 247
   at LamestWebserver.RequestHandlers.PageResponseRequestHandler.GetRetriableResponse(GetContents requestFunction, HttpRequest requestPacket, HttpSessionData sessionData) in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\RequestHandlers\RequestHandler.cs:line 1282
   at LamestWebserver.RequestHandlers.AbstractMutexRetriableResponse`1.GetResponse(HttpRequest requestPacket, Stopwatch currentStopwatch) in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\RequestHandlers\RequestHandler.cs:line 1154
   at LamestWebserver.RequestHandlers.RequestHandler.GetResponse(HttpRequest requestPacket) in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\RequestHandlers\RequestHandler.cs:line 117
   at LamestWebserver.WebServer.HandleClient(Object obj) in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\WebServer.cs:line 625
   at LamestWebserver.WebServer.<>c__DisplayClass45_0.<HandleTcpListener>b__0() in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\WebServer.cs:line 378
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at LamestWebserver.Core.ThreadedWorker.Work() in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\Core\ThreadedWorker.cs:line 226
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by rainerzufalldererste** [comment]
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at LamestWebserver.Master.GetErrorMsg(String title, String message)
   at LamestWebserver.RequestHandlers.ErrorRequestHandler.GetResponse(HttpRequest requestPacket, Stopwatch currentStopwatch) in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\RequestHandlers\RequestHandler.cs:line 1074
   at LamestWebserver.RequestHandlers.RequestHandler.GetResponse(HttpRequest requestPacket) in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\RequestHandlers\RequestHandler.cs:line 130
   at LamestWebserver.WebServer.HandleClient(Object obj) in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\WebServer.cs:line 631
   at LamestWebserver.WebServer.<>c__DisplayClass46_0.<HandleTcpListener>b__0() in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\WebServer.cs:line 384
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at LamestWebserver.Core.ThreadedWorker.Work() in H:\git\private\LamestWebserver\LamestWebserver\LamestWebserver\Core\ThreadedWorker.cs:line 226
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by rainerzufalldererste** [comment]
Fixed by moving executable from Network Drive to local folder.
